import LegalPageLayout, { LegalSection } from '@/components/LegalPageLayout';

const CONTACT_EMAIL = 'aleemyaseen39@gmail.com';
const COMPANY_NAME = 'AdMafia';

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" updated="September 28, 2026">
      <p className="text-sm leading-relaxed text-gray-600">
        These Terms of Service govern your use of AdMafia, an AI-assisted ad creation and publishing tool operated by
        {' '}{COMPANY_NAME}. By creating an account or using AdMafia, you agree to these terms.
      </p>

      <LegalSection title="1. What AdMafia does">
        <p>AdMafia lets you connect Meta, Google Ads, and TikTok ad accounts; write a campaign brief and optionally add product links or upload product photos; generate ad copy and ad creative using an AI provider (OpenAI); review and approve that output; and publish it to your connected ad accounts, where AdMafia can also retrieve performance metrics for ads you've published.</p>
      </LegalSection>

      <LegalSection title="2. Your account">
        <p>You must provide accurate information to create an account and are responsible for keeping your login credentials secure. You're responsible for all activity that happens under your account.</p>
      </LegalSection>

      <LegalSection title="3. Connecting third-party ad accounts">
        <p>When you connect a Meta, Google Ads, or TikTok account, you authorize AdMafia to access that account via the OAuth permissions you grant, including discovering ad accounts, publishing ads, and reading performance data. You represent that you're authorized to connect and manage the ad accounts you connect. You can disconnect an account at any time; see our <a href="/data-deletion" className="font-medium text-gray-900 underline">Data Deletion</a> page and <a href="/privacy" className="font-medium text-gray-900 underline">Privacy Policy</a> for how to fully revoke access.</p>
      </LegalSection>

      <LegalSection title="4. AI-generated content">
        <p>Ad copy and images are generated by an AI provider based on the brief, links, and photos you supply. You are responsible for reviewing and approving generated content before it's published, and for ensuring it's accurate, lawful, and compliant with the advertising policies of each platform you publish to. AdMafia does not guarantee that generated content is error-free, or that it will be approved by any ad platform.</p>
      </LegalSection>

      <LegalSection title="5. Acceptable use">
        <p>You agree not to use AdMafia to generate or publish content that is illegal, infringes someone else's rights, or violates the terms of service of Meta, Google, TikTok, or OpenAI. You agree not to attempt to circumvent the plan limits or security of the app.</p>
      </LegalSection>

      <LegalSection title="6. Plans and usage limits">
        <p>AdMafia offers Starter, Growth, and Agency plans with different monthly AI generation limits, as shown in the app. Changing your plan updates your account's stored plan and limits directly within the app.</p>
      </LegalSection>

      <LegalSection title="7. Data and privacy">
        <p>Our <a href="/privacy" className="font-medium text-gray-900 underline">Privacy Policy</a> describes what data we collect and how we use it, including what we share with Supabase (our database/storage/auth/backend provider), OpenAI (for generation), Netlify (hosting), and the ad platforms you connect.</p>
      </LegalSection>

      <LegalSection title="8. Termination">
        <p>You may stop using AdMafia and delete your account at any time — see our <a href="/data-deletion" className="font-medium text-gray-900 underline">Data Deletion</a> page. We may suspend or terminate accounts that violate these terms.</p>
      </LegalSection>

      <LegalSection title="9. Disclaimers">
        <p>AdMafia is provided "as is." We don't guarantee uninterrupted availability, that generated ad content will perform any particular way, or that any connected ad platform will accept or approve content you publish through AdMafia.</p>
      </LegalSection>

      <LegalSection title="10. Changes to these terms">
        <p>We may update these terms from time to time. Continued use of AdMafia after an update means you accept the revised terms.</p>
      </LegalSection>

      <LegalSection title="11. Contact us">
        <p>Questions about these terms can be sent to {CONTACT_EMAIL}.</p>
      </LegalSection>
    </LegalPageLayout>
  );
}
